export const countries = [
  // Always first
  { code: "+1", label: "United States", emoji: "🇺🇸" },

  // Alphabetical
  { code: "+93", label: "Afghanistan", emoji: "🇦🇫" },
  { code: "+355", label: "Albania", emoji: "🇦🇱" },
  { code: "+213", label: "Algeria", emoji: "🇩🇿" },
  { code: "+1", label: "American Samoa", emoji: "🇦🇸" },
  { code: "+376", label: "Andorra", emoji: "🇦🇩" },
  { code: "+244", label: "Angola", emoji: "🇦🇴" },
  { code: "+1", label: "Anguilla", emoji: "🇦🇮" },
  { code: "+1", label: "Antigua and Barbuda", emoji: "🇦🇬" },
  { code: "+54", label: "Argentina", emoji: "🇦🇷" },
  { code: "+374", label: "Armenia", emoji: "🇦🇲" },
  { code: "+297", label: "Aruba", emoji: "🇦🇼" },
  { code: "+61", label: "Australia", emoji: "🇦🇺" },
  { code: "+43", label: "Austria", emoji: "🇦🇹" },
  { code: "+994", label: "Azerbaijan", emoji: "🇦🇿" },
  { code: "+1", label: "Bahamas", emoji: "🇧🇸" },
  { code: "+973", label: "Bahrain", emoji: "🇧🇭" },
  { code: "+880", label: "Bangladesh", emoji: "🇧🇩" },
  { code: "+1", label: "Barbados", emoji: "🇧🇧" },
  { code: "+375", label: "Belarus", emoji: "🇧🇾" },
  { code: "+32", label: "Belgium", emoji: "🇧🇪" },
  { code: "+501", label: "Belize", emoji: "🇧🇿" },
  { code: "+229", label: "Benin", emoji: "🇧🇯" },
  { code: "+1", label: "Bermuda", emoji: "🇧🇲" },
  { code: "+975", label: "Bhutan", emoji: "🇧🇹" },
  { code: "+591", label: "Bolivia", emoji: "🇧🇴" },
  { code: "+387", label: "Bosnia and Herzegovina", emoji: "🇧🇦" },
  { code: "+267", label: "Botswana", emoji: "🇧🇼" },
  { code: "+55", label: "Brazil", emoji: "🇧🇷" },
  { code: "+246", label: "British Indian Ocean Territory", emoji: "🇮🇴" },
  { code: "+673", label: "Brunei", emoji: "🇧🇳" },
  { code: "+359", label: "Bulgaria", emoji: "🇧🇬" },
  { code: "+226", label: "Burkina Faso", emoji: "🇧🇫" },
  { code: "+257", label: "Burundi", emoji: "🇧🇮" },
  { code: "+855", label: "Cambodia", emoji: "🇰🇭" },
  { code: "+237", label: "Cameroon", emoji: "🇨🇲" },
  { code: "+1", label: "Canada", emoji: "🇨🇦" },
  { code: "+238", label: "Cape Verde", emoji: "🇨🇻" },
  { code: "+1", label: "Cayman Islands", emoji: "🇰🇾" },
  { code: "+236", label: "Central African Republic", emoji: "🇨🇫" },
  { code: "+235", label: "Chad", emoji: "🇹🇩" },
  { code: "+56", label: "Chile", emoji: "🇨🇱" },
  { code: "+86", label: "China", emoji: "🇨🇳" },
  { code: "+61", label: "Christmas Island", emoji: "🇨🇽" },
  { code: "+61", label: "Cocos (Keeling) Islands", emoji: "🇨🇨" },
  { code: "+57", label: "Colombia", emoji: "🇨🇴" },
  { code: "+269", label: "Comoros", emoji: "🇰🇲" },
  { code: "+242", label: "Congo", emoji: "🇨🇬" },
  { code: "+243", label: "Congo (DRC)", emoji: "🇨🇩" },
  { code: "+682", label: "Cook Islands", emoji: "🇨🇰" },
  { code: "+506", label: "Costa Rica", emoji: "🇨🇷" },
  { code: "+225", label: "Côte d'Ivoire", emoji: "🇨🇮" },
  { code: "+385", label: "Croatia", emoji: "🇭🇷" },
  { code: "+53", label: "Cuba", emoji: "🇨🇺" },
  { code: "+599", label: "Curaçao", emoji: "🇨🇼" },
  { code: "+357", label: "Cyprus", emoji: "🇨🇾" },
  { code: "+420", label: "Czech Republic", emoji: "🇨🇿" },
  { code: "+45", label: "Denmark", emoji: "🇩🇰" },
  { code: "+253", label: "Djibouti", emoji: "🇩🇯" },
  { code: "+1", label: "Dominica", emoji: "🇩🇲" },
  { code: "+1", label: "Dominican Republic", emoji: "🇩🇴" },
  { code: "+593", label: "Ecuador", emoji: "🇪🇨" },
  { code: "+20", label: "Egypt", emoji: "🇪🇬" },
  { code: "+503", label: "El Salvador", emoji: "🇸🇻" },
  { code: "+240", label: "Equatorial Guinea", emoji: "🇬🇶" },
  { code: "+291", label: "Eritrea", emoji: "🇪🇷" },
  { code: "+372", label: "Estonia", emoji: "🇪🇪" },
  { code: "+251", label: "Ethiopia", emoji: "🇪🇹" },
  { code: "+500", label: "Falkland Islands", emoji: "🇫🇰" },
  { code: "+298", label: "Faroe Islands", emoji: "🇫🇴" },
  { code: "+679", label: "Fiji", emoji: "🇫🇯" },
  { code: "+358", label: "Finland", emoji: "🇫🇮" },
  { code: "+33", label: "France", emoji: "🇫🇷" },
  { code: "+594", label: "French Guiana", emoji: "🇬🇫" },
  { code: "+689", label: "French Polynesia", emoji: "🇵🇫" },
  { code: "+241", label: "Gabon", emoji: "🇬🇦" },
  { code: "+220", label: "Gambia", emoji: "🇬🇲" },
  { code: "+995", label: "Georgia", emoji: "🇬🇪" },
  { code: "+49", label: "Germany", emoji: "🇩🇪" },
  { code: "+233", label: "Ghana", emoji: "🇬🇭" },
  { code: "+350", label: "Gibraltar", emoji: "🇬🇮" },
  { code: "+30", label: "Greece", emoji: "🇬🇷" },
  { code: "+299", label: "Greenland", emoji: "🇬🇱" },
  { code: "+1", label: "Grenada", emoji: "🇬🇩" },
  { code: "+590", label: "Guadeloupe", emoji: "🇬🇵" },
  { code: "+1", label: "Guam", emoji: "🇬🇺" },
  { code: "+502", label: "Guatemala", emoji: "🇬🇹" },
  { code: "+224", label: "Guinea", emoji: "🇬🇳" },
  { code: "+245", label: "Guinea-Bissau", emoji: "🇬🇼" },
  { code: "+592", label: "Guyana", emoji: "🇬🇾" },
  { code: "+509", label: "Haiti", emoji: "🇭🇹" },
  { code: "+39", label: "Holy See", emoji: "🇻🇦" },
  { code: "+504", label: "Honduras", emoji: "🇭🇳" },
  { code: "+852", label: "Hong Kong", emoji: "🇭🇰" },
  { code: "+36", label: "Hungary", emoji: "🇭🇺" },
  { code: "+354", label: "Iceland", emoji: "🇮🇸" },
  { code: "+91", label: "India", emoji: "🇮🇳" },
  { code: "+62", label: "Indonesia", emoji: "🇮🇩" },
  { code: "+98", label: "Iran", emoji: "🇮🇷" },
  { code: "+964", label: "Iraq", emoji: "🇮🇶" },
  { code: "+353", label: "Ireland", emoji: "🇮🇪" },
  { code: "+972", label: "Israel", emoji: "🇮🇱" },
  { code: "+39", label: "Italy", emoji: "🇮🇹" },
  { code: "+1", label: "Jamaica", emoji: "🇯🇲" },
  { code: "+81", label: "Japan", emoji: "🇯🇵" },
  { code: "+962", label: "Jordan", emoji: "🇯🇴" },
  { code: "+7", label: "Kazakhstan", emoji: "🇰🇿" },
  { code: "+254", label: "Kenya", emoji: "🇰🇪" },
  { code: "+686", label: "Kiribati", emoji: "🇰🇮" },
  { code: "+850", label: "North Korea", emoji: "🇰🇵" },
  { code: "+82", label: "South Korea", emoji: "🇰🇷" },
  { code: "+965", label: "Kuwait", emoji: "🇰🇼" },
  { code: "+996", label: "Kyrgyzstan", emoji: "🇰🇬" },
  { code: "+856", label: "Laos", emoji: "🇱🇦" },
  { code: "+371", label: "Latvia", emoji: "🇱🇻" },
  { code: "+961", label: "Lebanon", emoji: "🇱🇧" },
  { code: "+266", label: "Lesotho", emoji: "🇱🇸" },
  { code: "+231", label: "Liberia", emoji: "🇱🇷" },
  { code: "+218", label: "Libya", emoji: "🇱🇾" },
  { code: "+423", label: "Liechtenstein", emoji: "🇱🇮" },
  { code: "+370", label: "Lithuania", emoji: "🇱🇹" },
  { code: "+352", label: "Luxembourg", emoji: "🇱🇺" },
  { code: "+853", label: "Macau", emoji: "🇲🇴" },
  { code: "+389", label: "North Macedonia", emoji: "🇲🇰" },
  { code: "+261", label: "Madagascar", emoji: "🇲🇬" },
  { code: "+265", label: "Malawi", emoji: "🇲🇼" },
  { code: "+60", label: "Malaysia", emoji: "🇲🇾" },
  { code: "+960", label: "Maldives", emoji: "🇲🇻" },
  { code: "+223", label: "Mali", emoji: "🇲🇱" },
  { code: "+356", label: "Malta", emoji: "🇲🇹" },
  { code: "+692", label: "Marshall Islands", emoji: "🇲🇭" },
  { code: "+596", label: "Martinique", emoji: "🇲🇶" },
  { code: "+222", label: "Mauritania", emoji: "🇲🇷" },
  { code: "+230", label: "Mauritius", emoji: "🇲🇺" },
  { code: "+262", label: "Mayotte", emoji: "🇾🇹" },
  { code: "+52", label: "Mexico", emoji: "🇲🇽" },
  { code: "+691", label: "Micronesia", emoji: "🇫🇲" },
  { code: "+373", label: "Moldova", emoji: "🇲🇩" },
  { code: "+377", label: "Monaco", emoji: "🇲🇨" },
  { code: "+976", label: "Mongolia", emoji: "🇲🇳" },
  { code: "+382", label: "Montenegro", emoji: "🇲🇪" },
  { code: "+1", label: "Montserrat", emoji: "🇲🇸" },
  { code: "+212", label: "Morocco", emoji: "🇲🇦" },
  { code: "+258", label: "Mozambique", emoji: "🇲🇿" },
  { code: "+95", label: "Myanmar", emoji: "🇲🇲" },
  { code: "+264", label: "Namibia", emoji: "🇳🇦" },
  { code: "+674", label: "Nauru", emoji: "🇳🇷" },
  { code: "+977", label: "Nepal", emoji: "🇳🇵" },
  { code: "+31", label: "Netherlands", emoji: "🇳🇱" },
  { code: "+687", label: "New Caledonia", emoji: "🇳🇨" },
  { code: "+64", label: "New Zealand", emoji: "🇳🇿" },
  { code: "+505", label: "Nicaragua", emoji: "🇳🇮" },
  { code: "+227", label: "Niger", emoji: "🇳🇪" },
  { code: "+234", label: "Nigeria", emoji: "🇳🇬" },
  { code: "+683", label: "Niue", emoji: "🇳🇺" },
  { code: "+672", label: "Norfolk Island", emoji: "🇳🇫" },
  { code: "+850", label: "North Korea", emoji: "🇰🇵" },
  { code: "+1", label: "Northern Mariana Islands", emoji: "🇲🇵" },
  { code: "+47", label: "Norway", emoji: "🇳🇴" },
  { code: "+968", label: "Oman", emoji: "🇴🇲" },
  { code: "+92", label: "Pakistan", emoji: "🇵🇰" },
  { code: "+680", label: "Palau", emoji: "🇵🇼" },
  { code: "+970", label: "Palestine", emoji: "🇵🇸" },
  { code: "+507", label: "Panama", emoji: "🇵🇦" },
  { code: "+675", label: "Papua New Guinea", emoji: "🇵🇬" },
  { code: "+595", label: "Paraguay", emoji: "🇵🇾" },
  { code: "+51", label: "Peru", emoji: "🇵🇪" },
  { code: "+63", label: "Philippines", emoji: "🇵🇭" },
  { code: "+48", label: "Poland", emoji: "🇵🇱" },
  { code: "+351", label: "Portugal", emoji: "🇵🇹" },
  { code: "+1", label: "Puerto Rico", emoji: "🇵🇷" },
  { code: "+974", label: "Qatar", emoji: "🇶🇦" },
  { code: "+242", label: "Republic of the Congo", emoji: "🇨🇬" },
  { code: "+40", label: "Romania", emoji: "🇷🇴" },
  { code: "+7", label: "Russia", emoji: "🇷🇺" },
  { code: "+250", label: "Rwanda", emoji: "🇷🇼" },
  { code: "+590", label: "Saint Barthélemy", emoji: "🇧🇱" },
  { code: "+290", label: "Saint Helena", emoji: "🇸🇭" },
  { code: "+1", label: "Saint Kitts and Nevis", emoji: "🇰🇳" },
  { code: "+1", label: "Saint Lucia", emoji: "🇱🇨" },
  { code: "+590", label: "Saint Martin", emoji: "🇲🇫" },
  { code: "+508", label: "Saint Pierre and Miquelon", emoji: "🇵🇲" },
  { code: "+1", label: "Saint Vincent and the Grenadines", emoji: "🇻🇨" },
  { code: "+685", label: "Samoa", emoji: "🇼🇸" },
  { code: "+378", label: "San Marino", emoji: "🇸🇲" },
  { code: "+239", label: "Sao Tome and Principe", emoji: "🇸🇹" },
  { code: "+966", label: "Saudi Arabia", emoji: "🇸🇦" },
  { code: "+221", label: "Senegal", emoji: "🇸🇳" },
  { code: "+381", label: "Serbia", emoji: "🇷🇸" },
  { code: "+248", label: "Seychelles", emoji: "🇸🇨" },
  { code: "+232", label: "Sierra Leone", emoji: "🇸🇱" },
  { code: "+65", label: "Singapore", emoji: "🇸🇬" },
  { code: "+1", label: "Sint Maarten", emoji: "🇸🇽" },
  { code: "+421", label: "Slovakia", emoji: "🇸🇰" },
  { code: "+386", label: "Slovenia", emoji: "🇸🇮" },
  { code: "+677", label: "Solomon Islands", emoji: "🇸🇧" },
  { code: "+252", label: "Somalia", emoji: "🇸🇴" },
  { code: "+27", label: "South Africa", emoji: "🇿🇦" },
  { code: "+211", label: "South Sudan", emoji: "🇸🇸" },
  { code: "+34", label: "Spain", emoji: "🇪🇸" },
  { code: "+94", label: "Sri Lanka", emoji: "🇱🇰" },
  { code: "+249", label: "Sudan", emoji: "🇸🇩" },
  { code: "+597", label: "Suriname", emoji: "🇸🇷" },
  { code: "+47", label: "Svalbard and Jan Mayen", emoji: "🇸🇯" },
  { code: "+268", label: "Eswatini", emoji: "🇸🇿" },
  { code: "+46", label: "Sweden", emoji: "🇸🇪" },
  { code: "+41", label: "Switzerland", emoji: "🇨🇭" },
  { code: "+963", label: "Syria", emoji: "🇸🇾" },
  { code: "+886", label: "Taiwan", emoji: "🇹🇼" },
  { code: "+992", label: "Tajikistan", emoji: "🇹🇯" },
  { code: "+255", label: "Tanzania", emoji: "🇹🇿" },
  { code: "+66", label: "Thailand", emoji: "🇹🇭" },
  { code: "+670", label: "Timor-Leste", emoji: "🇹🇱" },
  { code: "+228", label: "Togo", emoji: "🇹🇬" },
  { code: "+690", label: "Tokelau", emoji: "🇹🇰" },
  { code: "+676", label: "Tonga", emoji: "🇹🇴" },
  { code: "+1", label: "Trinidad and Tobago", emoji: "🇹🇹" },
  { code: "+216", label: "Tunisia", emoji: "🇹🇳" },
  { code: "+90", label: "Turkey", emoji: "🇹🇷" },
  { code: "+993", label: "Turkmenistan", emoji: "🇹🇲" },
  { code: "+1", label: "Turks and Caicos Islands", emoji: "🇹🇨" },
  { code: "+688", label: "Tuvalu", emoji: "🇹🇻" },
  { code: "+256", label: "Uganda", emoji: "🇺🇬" },
  { code: "+380", label: "Ukraine", emoji: "🇺🇦" },
  { code: "+971", label: "United Arab Emirates", emoji: "🇦🇪" },
  { code: "+44", label: "United Kingdom", emoji: "🇬🇧" },
  { code: "+598", label: "Uruguay", emoji: "🇺🇾" },
  { code: "+998", label: "Uzbekistan", emoji: "🇺🇿" },
  { code: "+678", label: "Vanuatu", emoji: "🇻🇺" },
  { code: "+58", label: "Venezuela", emoji: "🇻🇪" },
  { code: "+84", label: "Vietnam", emoji: "🇻🇳" },
  { code: "+1", label: "Virgin Islands (U.S.)", emoji: "🇻🇮" },
  { code: "+681", label: "Wallis and Futuna", emoji: "🇼🇫" },
  { code: "+212", label: "Western Sahara", emoji: "🇪🇭" },
  { code: "+967", label: "Yemen", emoji: "🇾🇪" },
  { code: "+260", label: "Zambia", emoji: "🇿🇲" },
  { code: "+263", label: "Zimbabwe", emoji: "🇿🇼" }
];

